jobs:
# jobs for the dv pipeline from CI thru TEST environment
# manifest gen for VISUALIZER
  - name: sample-manifest
    type: manifest
    steps:
      - IN: samplepipelinesdemo
      - IN: samplepipelinesdemo-opts
      - TASK: managed

#/ manifest gen for VISUALIZER
# TEST deployment for VISUALIZER to Amazon ECS
  - name: deploy-ecs
    type: deploy
    steps:
      - IN: sample-manifest
#      - IN: dv-params
      - IN: ecs-cluster
      - TASK: managed

# / TEST deployment for VISUALIZER to Amazon ECS

# Connect CI with dv-img resource
  - name: samplePipelinesTest_runCI
    type: runCI
    steps:
      - OUT: samplepipelinesdemo

# / Connect CI with dv-img resource
  - name: samplepipelinesdemo-release
    type: release
    steps:
      - IN: samplepipelinesdemo-verion
        switch: on
      - IN: ecs-cluster
        switch: on
      - IN: dv-trigger
        switch: on
      - TASK: managed
        bump: minor

   - name: samplepipelinesdemo-prod-ecs
     type: deploy
     steps:
      - IN: samplepipelinesdemo-release
        switch: on
      - IN: ecs-cluster
      - TASK: managed
