jobs:

# jobs for the dv pipeline from CI thru TEST environment


# manifest gen for VISUALIZER
  - name: dv-man
    type: manifest
    steps:
      - IN: samplepipelinesdemo
      - IN: samplepipelinesdemo-opts
      - TASK: managed

#/ manifest gen for VISUALIZER

# TEST deployment for VISUALIZER to Amazon ECS
  - name: ecs-cluster
    type: deploy
    steps:
      - IN: samplepipelinesdemo
#      - IN: dv-params
      - IN: ecs-cluster
      - TASK: managed

# / TEST deployment for VISUALIZER to Amazon ECS

# Connect CI with dv-img resource
  - name: samplePipelinesDemo_runCI
    type: runCI
    steps:
      - OUT: samplepipelinesdemo
# / Connect CI with dv-img resource

